name: CD React App

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  
jobs:
  build:
    name: Build and Configure Versions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Definindo a versão do Node
      #   uses: actions/setup-node@v4
      #   with: 
      #     node-version: '22'

      - name: Make Scripts Executable
        run: |
          chmod +x build.sh

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker Image
        run: ./build.sh

      - name: Gerar artefato GitHub com os arquivos de build 
        uses: actions/upload-artifact@v4 
        with: 
          name: build-artifacts 
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Criar arquivo .pem a partir da variável DEPLOY_KEY e fazer o chmod 400 nele
        id: geracao-arquivo-pem
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" >> $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
      
